model:
  default: cloud-sanitized-auto
  context_length: 131072
  provider: custom
  base_url: http://litellm:4000/v1
  api_mode: chat_completions
providers:
  custom:
    api: http://litellm:4000/v1
    name: custom
    api_key: sk-dummy
auxiliary:
  title_generation:
    provider: custom
    base_url: http://litellm:4000/v1
    api_key: sk-dummy
    model: cloud-sanitized-auto
  compression:
    provider: custom
    base_url: http://litellm:4000/v1
    api_key: sk-dummy
    model: cloud-sanitized-auto
  web_extract:
    provider: custom
    base_url: http://litellm:4000/v1
    api_key: sk-dummy
    model: cloud-sanitized-auto
  skills_hub:
    provider: custom
    base_url: http://litellm:4000/v1
    api_key: sk-dummy
    model: cloud-sanitized-auto
  approval:
    provider: custom
    base_url: http://litellm:4000/v1
    api_key: sk-dummy
    model: cloud-sanitized-auto
onboarding:
  seen:
    busy_input_prompt: true
